[build]
  publish = "build"  # or "dist" or "public" depending on your build output
  command = "npm run build"  # or your build command

[[redirects]]
  from = "/api/*"
  to = "https://server1kingmaker.netlify.app/:splat"
  status = 200
  force = true