[[headers]]
  for = "/imagehost/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://scraper-initializer.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/imagehost/*"
  to = "/imagehost/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://scraper-initializer.netlify.app", Access-Control-Allow-Credentials = "true"}